version: "3.4"

services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    image: quay.io/shazchaudhry/docker-jenkins:latest
    environment:
      - JENKINS_HOME='/var/jenkins_home'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    deploy:

volumes:
  jenkins_home:
